### ISSUE TITLE
Slowness

### ISSUE THREAD

**Issue by johnjreiser** [cfh294/NJMunicipalMergerProject#1]
Connor, you should look into running the Polygon_Analysis function once, storing the results as a global table. This has it running on each iteration and then iterating over the results several times. I think you'd probably get a speed bump out of making sure it's only run once for the complete set of polygon-polygon interactions. I wasn't aware of that tool, it's pretty cool (and available at all license levels). If you're interested, I can show you how to recreate that function in PostGIS.

**Comment by cfh294** [comment]
Anything for a speed bump, this thing takes forever

**Comment by cfh294** [comment]
actually i think it has to run it on each iteration. i use the term iteration for each time a round of merges occurs, so 10 merges can occur on one iteration. Usually each county requires two to four iterations to get all of the merges done. After each iteration the new munis have their mun codes changed from null to whatever number merge they were so that they can be recognized as a municipality. If another round of merges is needed, the poly analysis tool would need to be run again in order to get the values for the merge key, now using those new mun codes as well. there may still be a faster way of doing this, but i'm pretty sure i still have to run the poly analysis tool each iteration

**Comment by johnjreiser** [comment]
Because you know the population sizes before you do any geometry hacking, couldn't the code be refactored to select the features to be merged and merge them in a group, instead of iteratively? Not grouping them all together, but clustering the munis that are to be merged and then merge. Post-merge, recalculate the whole state.
